Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -1,12 +1,45 @@
 version: 0.2
 
+env:
+  variables:
+    STAGE: $STAGE
+    DYNAMODB_TABLE_NAME: $DYNAMODB_TABLE_NAME
+    S3_BUCKET: $S3_BUCKET
+    TEMPLATE_FILE: $TEMPLATE_FILE
+    LAMBDA_FUNCTION_NAME: $LAMBDA_FUNCTION_NAME
+    STACK_NAME: $STACK_NAME
+    REGION: $REGION
+
 phases:
+  install:
+    runtime-versions:
+      nodejs: 18  # Use the Node.js version you need
+    commands:
+      - echo "Checking if AWS SAM is installed..."
+      - if ! command -v sam &> /dev/null; then
+          echo "AWS SAM not found. Installing...";
+          npm install -g aws-sam-cli;
+        else
+          echo "AWS SAM is already installed.";
+        fi
+
+  pre_build:
+    commands:
+      - echo "Checking if S3 bucket exists..."
+      - if ! aws s3 ls "s3://$S3_BUCKET"; then
+          echo "S3 bucket $S3_BUCKET does not exist. Creating...";
+          aws s3 mb "s3://$S3_BUCKET" --region $REGION;
+        else
+          echo "S3 bucket $S3_BUCKET already exists.";
+        fi
+
   build:
     commands:
-      - echo "Starting Deployment..."
-      - chmod +x shellScript/deploy/deploy.sh  # Make deploy.sh executable
-      - ./shellScript/deploy/deploy.sh  # Run the deployment script
+      - echo "Packaging application..."
+      - sam package --template-file $TEMPLATE_FILE --s3-bucket $S3_BUCKET --output-template-file packagedDeploy-template.yaml --region $REGION
 
   post_build:
     commands:
-      - echo "Deployment completed successfully!"
+      - echo "Deploying application..."
+      - sam deploy --template-file packagedDeploy-template.yaml --stack-name $STACK_NAME --s3-bucket $S3_BUCKET --region $REGION --no-fail-on-empty-changeset --capabilities CAPABILITY_NAMED_IAM CAPABILITY_IAM --parameter-overrides Stage=$STAGE DynamoDBTableName=$DYNAMODB_TABLE_NAME LambdaFunctionName=$LAMBDA_FUNCTION_NAME --tags created_by="vignesh" purpose="learning"
+      - echo "Deployment complete!"
